In [1]:
print("Hello")
print("good morning")

Hello
good morning


In [4]:
from numpy import *
arr1=array([2,4,6,1])
print(arr1)

[2 4 6 1]


In [5]:
print(type[arr1])

type[array([2, 4, 6, 1])]


In [6]:
from numpy import *
arr2=array(['Hello','hi','hey'])
arr3=arr2
print(arr2)
print(type(arr3))

['Hello' 'hi' 'hey']
<class 'numpy.ndarray'>


In [7]:
 from numpy import *
arr4=array([4,5,6,7])
arr4=arr4+5
print(arr4)

[ 9 10 11 12]


In [10]:
ar1=array([2,3,4,5])
ar2=array([3,4,5,6])
ar3=ar1+ar2
print(ar3)

[ 5  7  9 11]


In [ ]:
#2D Array

In [11]:
from numpy import *
ar1=array([
    [2,3,4],
    [5,6,7]
])
print(ar1.dtype)

int64


In [12]:
print(ar1.ndim)
print(ar1.shape)

2
(2, 3)


In [14]:
print(ar1.size)

6


In [ ]:
#2-d to 1-d
#flatten

In [15]:
ar2=ar1.flatten()
print(ar2)

[2 3 4 5 6 7]


In [16]:
#1-d to 2-D
#reshape
ar3=ar2.reshape(3,2)
print(ar3)

[[2 3]
 [4 5]
 [6 7]]


In [19]:
ar4=ar3.reshape(6,1)
print(ar4)

[[2]
 [3]
 [4]
 [5]
 [6]
 [7]]


In [20]:
ar1=zeros(5)
print(ar1)
print(type(ar1))

[0. 0. 0. 0. 0.]
<class 'numpy.ndarray'>


# linspace

In [22]:
ar1=linspace(1,3,10)
print(ar1)

[1.         1.22222222 1.44444444 1.66666667 1.88888889 2.11111111
 2.33333333 2.55555556 2.77777778 3.        ]


In [ ]:
#range


In [23]:
ar1=arange(1,15,2)
print(ar1)

[ 1  3  5  7  9 11 13]
